//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptekApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.TagMeds = new HashSet<TagMed>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Qr_Code { get; set; }
        public string Description { get; set; }
        public Nullable<byte> WithRecept { get; set; }
        public Nullable<System.DateTime> Pro_date { get; set; }
        public Nullable<System.DateTime> Valid_date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Firm_id { get; set; }
    
        public virtual Firm Firm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagMed> TagMeds { get; set; }
    }
}
